# fly.toml app configuration file generated for computer-help on 2025-01-27
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'computer-help'
primary_region = 'ams'

[build]

[env]
  PORT = "8765"

[http_service]
  internal_port = 8765
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
