import nodemailer from 'nodemailer';

// Create Gmail SMTP transporter
export const createTransporter = () => {
  return nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: process.env.GMAIL_USER, // Your Gmail address
      pass: process.env.GMAIL_APP_PASSWORD // Gmail App Password (not your regular password)
    }
  });
};

// Send admin approval request email
export async function sendAdminApprovalRequest(request) {
  const transporter = createTransporter();
  
  const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || 'https://codeclinic.nl';
  const approveUrl = `${baseUrl}/api/admin-access/action?token=${request.approveToken}&action=approve&requestId=${request.id}`;
  const denyUrl = `${baseUrl}/api/admin-access/action?token=${request.denyToken}&action=deny&requestId=${request.id}`;

  const subject = `🔐 Admin Access Request - ${request.name}`;
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">🔐 Admin Access Request</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">CodeClinic Admin Panel</p>
      </div>
      
      <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-top: 0;">New Admin Access Request</h2>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #007bff;">
          <p style="margin: 0 0 10px 0;"><strong>👤 Name:</strong> ${request.name}</p>
          <p style="margin: 0 0 10px 0;"><strong>📧 Email:</strong> ${request.email}</p>
          <p style="margin: 0 0 10px 0;"><strong>📅 Requested:</strong> ${new Date(request.createdAt).toLocaleString('nl-NL')}</p>
          ${request.reason ? `<p style="margin: 0;"><strong>💬 Reason:</strong> ${request.reason}</p>` : ''}
        </div>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${approveUrl}" 
             style="background: #28a745; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; margin: 0 10px; display: inline-block; font-weight: bold;">
            ✅ Approve Access
          </a>
          <a href="${denyUrl}" 
             style="background: #dc3545; color: white; padding: 15px 30px; text-decoration: none; border-radius: 5px; margin: 0 10px; display: inline-block; font-weight: bold;">
            ❌ Deny Access
          </a>
        </div>
        
        <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p style="margin: 0; color: #856404;"><strong>⚠️ Security Note:</strong> These links are secure and will expire after use. Only click if you recognize this person and want to grant them admin access.</p>
        </div>
        
        <p style="color: #666; font-size: 14px; margin-top: 30px;">
          This request was automatically generated by the CodeClinic admin access system.
        </p>
      </div>
    </div>
  `;

  const text = `
Admin Access Request - CodeClinic

New admin access request received:

Name: ${request.name}
Email: ${request.email}
Requested: ${new Date(request.createdAt).toLocaleString('nl-NL')}
${request.reason ? `Reason: ${request.reason}` : ''}

To approve: ${approveUrl}
To deny: ${denyUrl}

Security Note: These links are secure and will expire after use.
  `;

  try {
    const info = await transporter.sendMail({
      from: `"CodeClinic Admin" <${process.env.GMAIL_USER}>`,
      to: process.env.ADMIN_EMAIL || 'codeclinic.nl@gmail.com',
      subject: subject,
      html: html,
      text: text,
    });

    console.log('[email-service] Approval request sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('[email-service] Failed to send approval request:', error);
    throw error;
  }
}

// Send initial confirmation email when user requests access
export async function sendAccessRequestConfirmation(email, name) {
  const transporter = createTransporter();
  
  const subject = '📧 Admin Access Request Received - CodeClinic';
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #007bff 0%, #0056b3 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">📧 Request Received</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">CodeClinic Admin Panel</p>
      </div>
      
      <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-top: 0;">Hello ${name},</h2>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #007bff;">
          <p style="margin: 0 0 15px 0; color: #007bff; font-weight: bold;">✅ Your admin access request has been received!</p>
          <p style="margin: 0 0 15px 0;">We have received your request for admin access to the CodeClinic system. Our administrator will review your request and respond shortly.</p>
          <p style="margin: 0; font-weight: bold;">⏳ Please be patient while we process your request.</p>
        </div>
        
        <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p style="margin: 0; color: #856404;"><strong>📋 What happens next:</strong></p>
          <ul style="margin: 10px 0 0 0; color: #856404;">
            <li>Our administrator will review your request</li>
            <li>You will receive an email notification once a decision is made</li>
            <li>If approved, you can access the admin panel using your email</li>
          </ul>
        </div>
        
        <p style="color: #666; font-size: 14px; margin-top: 30px;">
          This confirmation was sent automatically by the CodeClinic admin access system.
        </p>
      </div>
    </div>
  `;

  const text = `
Admin Access Request Received - CodeClinic

Hello ${name},

✅ Your admin access request has been received!

We have received your request for admin access to the CodeClinic system. Our administrator will review your request and respond shortly.

⏳ Please be patient while we process your request.

What happens next:
- Our administrator will review your request
- You will receive an email notification once a decision is made
- If approved, you can access the admin panel using your email

This confirmation was sent automatically by the CodeClinic admin access system.
  `;

  try {
    const info = await transporter.sendMail({
      from: `"CodeClinic Admin" <${process.env.GMAIL_USER}>`,
      to: email,
      subject: subject,
      html: html,
      text: text,
    });

    console.log('[email-service] Access request confirmation sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('[email-service] Failed to send access request confirmation:', error);
    throw error;
  }
}

// Send customer booking confirmation email
export async function sendBookingConfirmation(booking) {
  const transporter = createTransporter();
  
  const subject = '📅 Afspraak Bevestigd - CodeClinic';
  
  const appointmentType = booking.appointment_type || 'onsite';
  const typeText = appointmentType === 'remote' ? 'Remote hulp' : 'Aan huis bezoek';
  const typeEmoji = appointmentType === 'remote' ? '💻' : '🏠';
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, #28a745 0%, #20c997 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">${typeEmoji} Afspraak Bevestigd!</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">CodeClinic Computer Hulp</p>
      </div>
      
      <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-top: 0;">Hallo ${booking.name},</h2>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #28a745;">
          <p style="margin: 0 0 15px 0; color: #28a745; font-weight: bold;">✅ Uw afspraak is succesvol geboekt!</p>
          <p style="margin: 0 0 15px 0;">Bedankt voor het boeken van een afspraak bij CodeClinic. Hier zijn de details van uw afspraak:</p>
        </div>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border: 1px solid #e9ecef;">
          <h3 style="color: #333; margin-top: 0;">📋 Afspraak Details</h3>
          <p style="margin: 5px 0;"><strong>Type:</strong> ${typeText} ${typeEmoji}</p>
          <p style="margin: 5px 0;"><strong>Datum:</strong> ${booking.date}</p>
          <p style="margin: 5px 0;"><strong>Tijd:</strong> ${booking.time}</p>
          <p style="margin: 5px 0;"><strong>Boekingsnummer:</strong> ${booking.booking_number || booking.id}</p>
          ${booking.notes ? `<p style="margin: 5px 0;"><strong>Notities:</strong> ${booking.notes}</p>` : ''}
        </div>
        
        <div style="background: #fff3cd; border: 1px solid #ffeaa7; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p style="margin: 0; color: #856404;"><strong>📞 Contact:</strong></p>
          <p style="margin: 5px 0; color: #856404;">Email: codeclinic.nl@gmail.com</p>
          <p style="margin: 5px 0; color: #856404;">Telefoon: [Uw telefoonnummer]</p>
        </div>
        
        <div style="background: #d1ecf1; border: 1px solid #bee5eb; padding: 15px; border-radius: 5px; margin: 20px 0;">
          <p style="margin: 0; color: #0c5460;"><strong>ℹ️ Belangrijke informatie:</strong></p>
          <ul style="margin: 10px 0 0 0; color: #0c5460;">
            <li>Houd deze bevestiging bij de hand</li>
            <li>Neem contact op als u de afspraak moet wijzigen</li>
            <li>Voor remote hulp: we sturen u een link vlak voor de afspraak</li>
            <li>Voor aan huis bezoek: we komen op het afgesproken tijdstip</li>
          </ul>
        </div>
        
        <p style="color: #666; font-size: 14px; margin-top: 30px;">
          Deze bevestiging werd automatisch verzonden door het CodeClinic boekingssysteem.
        </p>
      </div>
    </div>
  `;

  const text = `
Afspraak Bevestigd - CodeClinic

Hallo ${booking.name},

✅ Uw afspraak is succesvol geboekt!

Bedankt voor het boeken van een afspraak bij CodeClinic. Hier zijn de details van uw afspraak:

📋 Afspraak Details
Type: ${typeText} ${typeEmoji}
Datum: ${booking.date}
Tijd: ${booking.time}
Boekingsnummer: ${booking.booking_number || booking.id}
${booking.notes ? `Notities: ${booking.notes}` : ''}

📞 Contact:
Email: codeclinic.nl@gmail.com
Telefoon: [Uw telefoonnummer]

ℹ️ Belangrijke informatie:
- Houd deze bevestiging bij de hand
- Neem contact op als u de afspraak moet wijzigen
- Voor remote hulp: we sturen u een link vlak voor de afspraak
- Voor aan huis bezoek: we komen op het afgesproken tijdstip

Deze bevestiging werd automatisch verzonden door het CodeClinic boekingssysteem.
  `;

  try {
    const info = await transporter.sendMail({
      from: `"CodeClinic Computer Hulp" <${process.env.GMAIL_USER}>`,
      to: booking.email,
      subject: subject,
      html: html,
      text: text,
    });

    console.log('[email-service] Booking confirmation sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('[email-service] Failed to send booking confirmation:', error);
    throw error;
  }
}

// Send user notification email
export async function sendUserNotification(email, name, approved) {
  const transporter = createTransporter();
  
  const subject = approved 
    ? '✅ Admin Access Approved - CodeClinic' 
    : '❌ Admin Access Denied - CodeClinic';
  
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="background: linear-gradient(135deg, ${approved ? '#28a745' : '#dc3545'} 0%, ${approved ? '#20c997' : '#e74c3c'} 100%); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center;">
        <h1 style="margin: 0; font-size: 24px;">${approved ? '✅' : '❌'} Admin Access ${approved ? 'Approved' : 'Denied'}</h1>
        <p style="margin: 10px 0 0 0; opacity: 0.9;">CodeClinic Admin Panel</p>
      </div>
      
      <div style="background: #f8f9fa; padding: 30px; border-radius: 0 0 10px 10px; border: 1px solid #e9ecef;">
        <h2 style="color: #333; margin-top: 0;">Hello ${name},</h2>
        
        <div style="background: white; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid ${approved ? '#28a745' : '#dc3545'};">
          ${approved ? `
            <p style="margin: 0 0 15px 0; color: #28a745; font-weight: bold;">🎉 Your admin access request has been approved!</p>
            <p style="margin: 0;">You can now access the admin panel using your email address. Use the same method you used to request access to log in.</p>
          ` : `
            <p style="margin: 0 0 15px 0; color: #dc3545; font-weight: bold;">😔 Your admin access request has been denied.</p>
            <p style="margin: 0;">If you believe this is an error, please contact the administrator directly.</p>
          `}
        </div>
        
        <p style="color: #666; font-size: 14px; margin-top: 30px;">
          This notification was sent automatically by the CodeClinic admin access system.
        </p>
      </div>
    </div>
  `;

  const text = `
${approved ? 'Admin Access Approved' : 'Admin Access Denied'} - CodeClinic

Hello ${name},

${approved 
  ? 'Your admin access request has been approved! You can now access the admin panel using your email address.'
  : 'Your admin access request has been denied. If you believe this is an error, please contact the administrator directly.'
}

This notification was sent automatically by the CodeClinic admin access system.
  `;

  try {
    const info = await transporter.sendMail({
      from: `"CodeClinic Admin" <${process.env.GMAIL_USER}>`,
      to: email,
      subject: subject,
      html: html,
      text: text,
    });

    console.log('[email-service] User notification sent successfully:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('[email-service] Failed to send user notification:', error);
    throw error;
  }
}
