name: Simple Supabase Keep-Alive

# Run every 4 hours to keep Supabase active
on:
  schedule:
    - cron: '0 */4 * * *'  # Every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    
    steps:
    - name: Ping Keep-Alive Endpoint
      run: |
        echo "🔄 Pinging Supabase keep-alive endpoint..."
        
        # Your actual Vercel URL
        URL="https://codeclinic.nl/api/keepalive"
        
        # Ping the endpoint
        response=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
        
        if [ "$response" = "200" ]; then
          echo "✅ Keep-alive successful! (HTTP $response)"
        else
          echo "❌ Keep-alive failed! (HTTP $response)"
          exit 1
        fi
        
    - name: Ping Health Check
      run: |
        echo "🔄 Pinging health check endpoint..."
        
        # Your actual Vercel URL
        URL="https://codeclinic.nl/api/health"
        
        # Ping the endpoint
        response=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
        
        if [ "$response" = "200" ]; then
          echo "✅ Health check successful! (HTTP $response)"
        else
          echo "❌ Health check failed! (HTTP $response)"
          exit 1
        fi
